/**
 * Algaroshy Farm — Alarm Code Registry
 *
 * All 50 alarm codes from ALARM_MATRIX.md §9 with metadata.
 */

import type { AlarmSeverity, AlarmCategory } from "./enums.js";

export interface AlarmDefinition {
  code: string;
  name: string;
  name_ar: string;
  category: AlarmCategory;
  severity: AlarmSeverity;
  requires_ack: boolean;
  requires_manual_reset: boolean;
  description_en: string;
  description_ar: string;
}

export const ALARM_DEFINITIONS: Record<string, AlarmDefinition> = {
  "ALM-001": {
    code: "ALM-001",
    name: "Tank Low Level Warning",
    name_ar: "تحذير انخفاض مستوى الخزان",
    category: "water_source",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Tank level below warning threshold",
    description_ar: "مستوى الخزان أقل من حد التحذير",
  },
  "ALM-002": {
    code: "ALM-002",
    name: "Tank Critically Low Level",
    name_ar: "مستوى الخزان حرج",
    category: "water_source",
    severity: "S3",
    requires_ack: true,
    requires_manual_reset: false,
    description_en: "Tank level below critical threshold",
    description_ar: "مستوى الخزان أقل من الحد الحرج",
  },
  "ALM-003": {
    code: "ALM-003",
    name: "Tank Level Sensor Fault",
    name_ar: "عطل حساس مستوى الخزان",
    category: "equipment",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Invalid or missing tank sensor signal",
    description_ar: "إشارة حساس الخزان غير صالحة أو مفقودة",
  },
  "ALM-004": {
    code: "ALM-004",
    name: "Well Pump Fault / Trip",
    name_ar: "عطل / فصل مضخة البئر",
    category: "equipment",
    severity: "S3",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Pump overload, thermal trip, or feedback fault",
    description_ar: "حمل زائد أو فصل حراري أو خطأ في التغذية الراجعة",
  },
  "ALM-005": {
    code: "ALM-005",
    name: "Booster Pump Fault / Trip",
    name_ar: "عطل / فصل مضخة التعزيز",
    category: "equipment",
    severity: "S3",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Booster pump fault feedback active",
    description_ar: "تغذية راجعة خطأ مضخة التعزيز نشطة",
  },
  "ALM-006": {
    code: "ALM-006",
    name: "Booster Pump Failed to Start",
    name_ar: "فشل بدء تشغيل مضخة التعزيز",
    category: "equipment",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Start command sent but no run feedback within timeout",
    description_ar: "تم إرسال أمر التشغيل ولكن لا توجد تغذية راجعة للتشغيل",
  },
  "ALM-007": {
    code: "ALM-007",
    name: "Well Pump Failed to Start",
    name_ar: "فشل بدء تشغيل مضخة البئر",
    category: "equipment",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Start command sent but no run feedback within timeout",
    description_ar: "تم إرسال أمر التشغيل ولكن لا توجد تغذية راجعة للتشغيل",
  },
  "ALM-008": {
    code: "ALM-008",
    name: "Mainline Low Pressure Warning",
    name_ar: "تحذير ضغط منخفض في الخط الرئيسي",
    category: "process",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Pressure below warning threshold for debounce period",
    description_ar: "الضغط أقل من حد التحذير لفترة الاستقرار",
  },
  "ALM-009": {
    code: "ALM-009",
    name: "Mainline Critically Low Pressure",
    name_ar: "ضغط حرج في الخط الرئيسي",
    category: "process",
    severity: "S3",
    requires_ack: true,
    requires_manual_reset: false,
    description_en: "Pressure below critical threshold while irrigation expected",
    description_ar: "الضغط أقل من الحد الحرج أثناء توقع الري",
  },
  "ALM-010": {
    code: "ALM-010",
    name: "Mainline High Pressure Warning",
    name_ar: "تحذير ضغط مرتفع في الخط الرئيسي",
    category: "process",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Pressure above warning threshold",
    description_ar: "الضغط أعلى من حد التحذير",
  },
  "ALM-011": {
    code: "ALM-011",
    name: "Mainline Critically High Pressure",
    name_ar: "ضغط حرج مرتفع في الخط الرئيسي",
    category: "process",
    severity: "S3",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Pressure above critical threshold — equipment protection",
    description_ar: "الضغط أعلى من الحد الحرج — حماية المعدات",
  },
  "ALM-012": {
    code: "ALM-012",
    name: "No Flow Detected",
    name_ar: "لم يتم اكتشاف تدفق",
    category: "process",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: false,
    description_en: "Zone/pump commanded on, main flow below expected after delay",
    description_ar: "تم أمر تشغيل المنطقة/المضخة ولكن التدفق أقل من المتوقع",
  },
  "ALM-013": {
    code: "ALM-013",
    name: "Abnormal High Flow / Leak Suspected",
    name_ar: "تدفق غير طبيعي / اشتباه في تسرب",
    category: "process",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: false,
    description_en: "Flow above expected max band for current zone combination",
    description_ar: "التدفق أعلى من النطاق المتوقع لتركيبة المناطق الحالية",
  },
  "ALM-014": {
    code: "ALM-014",
    name: "Flow Meter Sensor Fault",
    name_ar: "عطل حساس التدفق",
    category: "equipment",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Flow signal invalid, frozen, or out of range",
    description_ar: "إشارة التدفق غير صالحة أو متجمدة أو خارج النطاق",
  },
  "ALM-015": {
    code: "ALM-015",
    name: "Pressure Sensor Fault",
    name_ar: "عطل حساس الضغط",
    category: "equipment",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Pressure signal invalid or frozen",
    description_ar: "إشارة الضغط غير صالحة أو متجمدة",
  },
  "ALM-016": {
    code: "ALM-016",
    name: "Soil Moisture Sensor Fault",
    name_ar: "عطل حساس رطوبة التربة",
    category: "equipment",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: true,
    description_en: "Moisture sensor invalid or offline",
    description_ar: "حساس الرطوبة غير صالح أو غير متصل",
  },
  "ALM-017": {
    code: "ALM-017",
    name: "Soil Moisture Too Low After Cycle",
    name_ar: "رطوبة التربة منخفضة جداً بعد الدورة",
    category: "process",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Moisture below expected after irrigation cycle",
    description_ar: "الرطوبة أقل من المتوقع بعد دورة الري",
  },
  "ALM-018": {
    code: "ALM-018",
    name: "Soil Moisture Too High / Overwatering Risk",
    name_ar: "رطوبة التربة مرتفعة / خطر الإفراط في الري",
    category: "process",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Moisture above target high band",
    description_ar: "الرطوبة أعلى من النطاق المستهدف",
  },
  "ALM-019": {
    code: "ALM-019",
    name: "Valve Failed to Open",
    name_ar: "فشل فتح الصمام",
    category: "equipment",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: false,
    description_en: "Open command issued but no feedback / derived success absent",
    description_ar: "تم إصدار أمر الفتح ولكن لا توجد تغذية راجعة",
  },
  "ALM-020": {
    code: "ALM-020",
    name: "Valve Failed to Close",
    name_ar: "فشل إغلاق الصمام",
    category: "equipment",
    severity: "S3",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Close command issued but valve remains open",
    description_ar: "تم إصدار أمر الإغلاق ولكن الصمام لا يزال مفتوحاً",
  },
  "ALM-021": {
    code: "ALM-021",
    name: "Unexpected Valve State Change",
    name_ar: "تغيير غير متوقع في حالة الصمام",
    category: "equipment",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Valve feedback changed without command",
    description_ar: "تغيرت تغذية الصمام الراجعة بدون أمر",
  },
  "ALM-022": {
    code: "ALM-022",
    name: "Zone Runtime Exceeded",
    name_ar: "تجاوز وقت تشغيل المنطقة",
    category: "process",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: false,
    description_en: "Zone active longer than configured max runtime",
    description_ar: "المنطقة نشطة لفترة أطول من الحد الأقصى المسموح",
  },
  "ALM-023": {
    code: "ALM-023",
    name: "Zone Start Conflict",
    name_ar: "تعارض في بدء تشغيل المنطقة",
    category: "configuration",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Requested zone combination not allowed",
    description_ar: "تركيبة المناطق المطلوبة غير مسموح بها",
  },
  "ALM-024": {
    code: "ALM-024",
    name: "Hydraulic Capacity Exceeded",
    name_ar: "تجاوز السعة الهيدروليكية",
    category: "process",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: false,
    description_en: "Zone combination exceeds pressure/flow capacity",
    description_ar: "تركيبة المناطق تتجاوز سعة الضغط/التدفق",
  },
  "ALM-025": {
    code: "ALM-025",
    name: "Invalid Schedule Configuration",
    name_ar: "تكوين جدول غير صالح",
    category: "configuration",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Schedule overlaps or has invalid parameters",
    description_ar: "الجدول يتداخل أو يحتوي على معايير غير صالحة",
  },
  "ALM-026": {
    code: "ALM-026",
    name: "Irrigation Cycle Aborted",
    name_ar: "تم إلغاء دورة الري",
    category: "process",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Sequence aborted due to fault or manual stop",
    description_ar: "تم إلغاء التسلسل بسبب خطأ أو إيقاف يدوي",
  },
  "ALM-027": {
    code: "ALM-027",
    name: "Dry-Run Risk",
    name_ar: "خطر التشغيل الجاف",
    category: "water_source",
    severity: "S3",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Dry-run protection triggered — pump stopped immediately",
    description_ar: "تم تفعيل حماية التشغيل الجاف — تم إيقاف المضخة فوراً",
  },
  "ALM-028": {
    code: "ALM-028",
    name: "Source Unavailable",
    name_ar: "المصدر غير متاح",
    category: "water_source",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: false,
    description_en: "Selected water source cannot be used",
    description_ar: "لا يمكن استخدام مصدر المياه المحدد",
  },
  "ALM-029": {
    code: "ALM-029",
    name: "Communication Lost — PLC to Backend",
    name_ar: "فقدان الاتصال — PLC إلى الخادم",
    category: "utility",
    severity: "S2",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Backend heartbeat missing from PLC/edge",
    description_ar: "نبضات الخادم مفقودة من PLC/الحافة",
  },
  "ALM-030": {
    code: "ALM-030",
    name: "Communication Lost — Backend to App Push",
    name_ar: "فقدان الاتصال — الخادم إلى الإشعارات",
    category: "utility",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Notification provider unavailable",
    description_ar: "مزود الإشعارات غير متاح",
  },
  "ALM-031": {
    code: "ALM-031",
    name: "Internet / Cloud Sync Lost",
    name_ar: "فقدان الإنترنت / المزامنة السحابية",
    category: "utility",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "WAN unavailable or cloud sync failing",
    description_ar: "شبكة الإنترنت غير متاحة أو فشل المزامنة",
  },
  "ALM-032": {
    code: "ALM-032",
    name: "GSM / SMS Gateway Fault",
    name_ar: "عطل بوابة GSM / SMS",
    category: "utility",
    severity: "S2",
    requires_ack: false,
    requires_manual_reset: true,
    description_en: "SMS module unavailable",
    description_ar: "وحدة الرسائل القصيرة غير متاحة",
  },
  "ALM-033": {
    code: "ALM-033",
    name: "Power Loss / Control Power Failure",
    name_ar: "انقطاع الطاقة / فشل طاقة التحكم",
    category: "utility",
    severity: "S3",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Control power lost or UPS absent",
    description_ar: "فقدان طاقة التحكم أو عدم وجود UPS",
  },
  "ALM-034": {
    code: "ALM-034",
    name: "PLC Restart / Warm Start Event",
    name_ar: "إعادة تشغيل PLC",
    category: "utility",
    severity: "S0",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "PLC rebooted or restarted",
    description_ar: "تم إعادة تشغيل PLC",
  },
  "ALM-035": {
    code: "ALM-035",
    name: "Unauthorized Command Attempt",
    name_ar: "محاولة أمر غير مصرح به",
    category: "security",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "User without permission attempted control command",
    description_ar: "محاولة مستخدم بدون صلاحية إرسال أمر تحكم",
  },
  "ALM-036": {
    code: "ALM-036",
    name: "Repeated Fault on Same Zone",
    name_ar: "خطأ متكرر في نفس المنطقة",
    category: "maintenance",
    severity: "S2",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Same zone triggers same fault repeatedly",
    description_ar: "نفس المنطقة تسبب نفس الخطأ بشكل متكرر",
  },
  "ALM-037": {
    code: "ALM-037",
    name: "Sensor Drift Suspected",
    name_ar: "اشتباه في انحراف الحساس",
    category: "maintenance",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Sensor deviates persistently from expected correlations",
    description_ar: "الحساس ينحرف باستمرار عن الارتباطات المتوقعة",
  },
  "ALM-038": {
    code: "ALM-038",
    name: "Maintenance Due — Pump",
    name_ar: "مطلوب صيانة — المضخة",
    category: "maintenance",
    severity: "S0",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Pump runtime/service interval exceeded",
    description_ar: "تم تجاوز فترة التشغيل/الصيانة للمضخة",
  },
  "ALM-039": {
    code: "ALM-039",
    name: "Maintenance Due — Filters / Valves",
    name_ar: "مطلوب صيانة — الفلاتر / الصمامات",
    category: "maintenance",
    severity: "S0",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Service interval reached for filters or valves",
    description_ar: "تم الوصول لفترة صيانة الفلاتر أو الصمامات",
  },
  "ALM-040": {
    code: "ALM-040",
    name: "Camera / CCTV Offline",
    name_ar: "الكاميرا / CCTV غير متصل",
    category: "utility",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Camera heartbeat lost (future phase)",
    description_ar: "فقدان نبضات الكاميرا (مرحلة مستقبلية)",
  },
  "ALM-041": {
    code: "ALM-041",
    name: "Emergency Stop Activated",
    name_ar: "تم تفعيل إيقاف الطوارئ",
    category: "utility",
    severity: "S3",
    requires_ack: true,
    requires_manual_reset: true,
    description_en: "Local E-stop input active — all equipment stopped",
    description_ar: "مدخل إيقاف الطوارئ المحلي نشط — تم إيقاف جميع المعدات",
  },
  "ALM-042": {
    code: "ALM-042",
    name: "Manual Mode Active",
    name_ar: "الوضع اليدوي نشط",
    category: "process",
    severity: "S0",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Zone or system in manual mode",
    description_ar: "المنطقة أو النظام في الوضع اليدوي",
  },
  "ALM-043": {
    code: "ALM-043",
    name: "Maintenance Mode Active",
    name_ar: "وضع الصيانة نشط",
    category: "process",
    severity: "S0",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Maintenance mode enabled",
    description_ar: "وضع الصيانة مفعل",
  },
  "ALM-044": {
    code: "ALM-044",
    name: "Data Stale / Last Good State Only",
    name_ar: "بيانات قديمة / آخر حالة جيدة فقط",
    category: "utility",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "UI data older than freshness threshold",
    description_ar: "بيانات الواجهة أقدم من حد الحداثة",
  },
  "ALM-045": {
    code: "ALM-045",
    name: "Cloud Backup Failure",
    name_ar: "فشل النسخ الاحتياطي السحابي",
    category: "utility",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Backup or archive job failed",
    description_ar: "فشل مهمة النسخ الاحتياطي أو الأرشفة",
  },
  "ALM-046": {
    code: "ALM-046",
    name: "Zone Not Watered as Expected",
    name_ar: "المنطقة لم تُروَ كما هو متوقع",
    category: "process",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: false,
    description_en: "Zone completed but irrigation validation was poor",
    description_ar: "تم إكمال المنطقة ولكن التحقق من الري كان ضعيفاً",
  },
  "ALM-047": {
    code: "ALM-047",
    name: "Excessive Start/Stop Cycling",
    name_ar: "دورات تشغيل/إيقاف مفرطة",
    category: "equipment",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: false,
    description_en: "Pumps/valves cycling too frequently",
    description_ar: "المضخات/الصمامات تتنقل بتردد مفرط",
  },
  "ALM-048": {
    code: "ALM-048",
    name: "Direct-Well Supply Not Permitted",
    name_ar: "التغذية المباشرة من البئر غير مسموحة",
    category: "configuration",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Zone requested on direct-well path but config disallows",
    description_ar: "المنطقة طلبت مسار البئر المباشر ولكن التكوين لا يسمح",
  },
  "ALM-049": {
    code: "ALM-049",
    name: "Source Switchover Failed",
    name_ar: "فشل تبديل المصدر",
    category: "water_source",
    severity: "S2",
    requires_ack: true,
    requires_manual_reset: false,
    description_en: "Automatic failover did not complete",
    description_ar: "لم يكتمل التبديل التلقائي",
  },
  "ALM-050": {
    code: "ALM-050",
    name: "Configuration Missing Thresholds",
    name_ar: "تكوين مفقود الحدود",
    category: "configuration",
    severity: "S1",
    requires_ack: false,
    requires_manual_reset: false,
    description_en: "Zone/device lacks required threshold values",
    description_ar: "المنطقة/الجهاز يفتقر لقيم الحدود المطلوبة",
  },
};
