/**
 * Algaroshy Farm — Seed Data Constants
 *
 * 12 zones extracted from farm layout SVG.
 * Total farm area: 11.90 ha | 119,004.91 m²
 */

import type { Zone, Pump, Sensor, WaterSource, Valve, Farm } from "./types.js";

// ─── Farm ───────────────────────────────────────────────

export const FARM_SEED: Farm = {
  id: "farm_algaroshy",
  name: "Algaroshy Farm",
  name_ar: "مزرعة الجروشي",
  description: "Smart automated irrigation system for Algaroshy Farm",
  timezone: "Africa/Tripoli",
  total_area_ha: 11.9,
  created_at: "2026-01-01T00:00:00Z",
};

// ─── 12 Zones (from farm layout) ────────────────────────

export const ZONE_SEEDS: Zone[] = [
  {
    id: "zone_rumman_1",
    farm_id: "farm_algaroshy",
    code: "RUMMAN_1",
    name: "Pomegranate 1",
    name_ar: "رمان 1",
    crop_type: "pomegranate",
    area_ha: 0.50,
    geometry_ref: null,
    enabled: true,
    priority: 1,
    source_preference: "tank",
    allows_direct_well: false,
    max_runtime_min: 90,
    default_duration_min: 45,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 2.0,
    flow_max_m3h: 8.0,
  },
  {
    id: "zone_rumman_2",
    farm_id: "farm_algaroshy",
    code: "RUMMAN_2",
    name: "Pomegranate 2",
    name_ar: "رمان 2",
    crop_type: "pomegranate",
    area_ha: 0.71,
    geometry_ref: null,
    enabled: true,
    priority: 2,
    source_preference: "tank",
    allows_direct_well: false,
    max_runtime_min: 90,
    default_duration_min: 60,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 3.0,
    flow_max_m3h: 10.0,
  },
  {
    id: "zone_rumman_3",
    farm_id: "farm_algaroshy",
    code: "RUMMAN_3",
    name: "Pomegranate 3",
    name_ar: "رمان 3",
    crop_type: "pomegranate",
    area_ha: 0.54,
    geometry_ref: null,
    enabled: true,
    priority: 3,
    source_preference: "tank",
    allows_direct_well: false,
    max_runtime_min: 90,
    default_duration_min: 45,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 2.5,
    flow_max_m3h: 8.0,
  },
  {
    id: "zone_rumman_4",
    farm_id: "farm_algaroshy",
    code: "RUMMAN_4",
    name: "Pomegranate 4",
    name_ar: "رمان 4",
    crop_type: "pomegranate",
    area_ha: 0.71,
    geometry_ref: null,
    enabled: true,
    priority: 4,
    source_preference: "tank",
    allows_direct_well: true,
    max_runtime_min: 90,
    default_duration_min: 60,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 3.0,
    flow_max_m3h: 10.0,
  },
  {
    id: "zone_rumman_5",
    farm_id: "farm_algaroshy",
    code: "RUMMAN_5",
    name: "Pomegranate 5",
    name_ar: "رمان 5",
    crop_type: "pomegranate",
    area_ha: 0.64,
    geometry_ref: null,
    enabled: true,
    priority: 5,
    source_preference: "tank",
    allows_direct_well: false,
    max_runtime_min: 90,
    default_duration_min: 50,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 2.5,
    flow_max_m3h: 9.0,
  },
  {
    id: "zone_rumman_6",
    farm_id: "farm_algaroshy",
    code: "RUMMAN_6",
    name: "Pomegranate 6",
    name_ar: "رمان 6",
    crop_type: "pomegranate",
    area_ha: 0.81,
    geometry_ref: null,
    enabled: true,
    priority: 6,
    source_preference: "tank",
    allows_direct_well: false,
    max_runtime_min: 120,
    default_duration_min: 60,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 3.0,
    flow_max_m3h: 11.0,
  },
  {
    id: "zone_rumman_ummahat",
    farm_id: "farm_algaroshy",
    code: "RUMMAN_UMMAHAT",
    name: "Pomegranate Mothers",
    name_ar: "رمان امهات",
    crop_type: "pomegranate",
    area_ha: 0.14,
    geometry_ref: null,
    enabled: true,
    priority: 7,
    source_preference: "tank",
    allows_direct_well: true,
    max_runtime_min: 60,
    default_duration_min: 30,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 1.0,
    flow_max_m3h: 4.0,
  },
  {
    id: "zone_rumman_jadeed",
    farm_id: "farm_algaroshy",
    code: "RUMMAN_JADEED",
    name: "New Pomegranate",
    name_ar: "رمان جديد",
    crop_type: "pomegranate",
    area_ha: 0.93,
    geometry_ref: null,
    enabled: true,
    priority: 8,
    source_preference: "tank",
    allows_direct_well: true,
    max_runtime_min: 120,
    default_duration_min: 60,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 3.5,
    flow_max_m3h: 12.0,
  },
  {
    id: "zone_zaytoun",
    farm_id: "farm_algaroshy",
    code: "ZAYTOUN",
    name: "Olives",
    name_ar: "زيتون",
    crop_type: "olives",
    area_ha: 2.29,
    geometry_ref: null,
    enabled: true,
    priority: 9,
    source_preference: "tank",
    allows_direct_well: false,
    max_runtime_min: 180,
    default_duration_min: 90,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 5.0,
    flow_max_m3h: 18.0,
  },
  {
    id: "zone_zaytoun_2",
    farm_id: "farm_algaroshy",
    code: "ZAYTOUN_2",
    name: "Olives 2",
    name_ar: "زيتون 2",
    crop_type: "olives",
    area_ha: 0.15,
    geometry_ref: null,
    enabled: true,
    priority: 10,
    source_preference: "tank",
    allows_direct_well: true,
    max_runtime_min: 60,
    default_duration_min: 30,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 1.0,
    flow_max_m3h: 4.0,
  },
  {
    id: "zone_enab",
    farm_id: "farm_algaroshy",
    code: "ENAB",
    name: "Grapes",
    name_ar: "عنب",
    crop_type: "grapes",
    area_ha: 0.07,
    geometry_ref: null,
    enabled: true,
    priority: 11,
    source_preference: "tank",
    allows_direct_well: true,
    max_runtime_min: 45,
    default_duration_min: 20,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 0.5,
    flow_max_m3h: 3.0,
  },
  {
    id: "zone_fruit_mix",
    farm_id: "farm_algaroshy",
    code: "FRUIT_MIX",
    name: "Peach + Apricot + Guava",
    name_ar: "خوخ + مشمش + كوبة",
    crop_type: "mixed_fruit",
    area_ha: 1.09,
    geometry_ref: null,
    enabled: true,
    priority: 12,
    source_preference: "tank",
    allows_direct_well: true,
    max_runtime_min: 120,
    default_duration_min: 60,
    pressure_min_bar: 1.5,
    pressure_max_bar: 4.0,
    flow_min_m3h: 4.0,
    flow_max_m3h: 14.0,
  },
];

// ─── Pumps ──────────────────────────────────────────────

export const PUMP_SEEDS: Pump[] = [
  {
    id: "pump_well_01",
    farm_id: "farm_algaroshy",
    code: "WELL_PUMP_01",
    name: "Well Pump",
    name_ar: "مضخة البئر",
    pump_type: "well",
    rated_flow_m3h: null, // TBD from field survey
    rated_pressure_bar: null,
    runtime_hours: 0,
    service_interval_hours: 2000,
    enabled: true,
  },
  {
    id: "pump_booster_01",
    farm_id: "farm_algaroshy",
    code: "BOOSTER_PUMP_01",
    name: "Booster Pump",
    name_ar: "مضخة التعزيز",
    pump_type: "booster",
    rated_flow_m3h: null,
    rated_pressure_bar: null,
    runtime_hours: 0,
    service_interval_hours: 2000,
    enabled: true,
  },
];

// ─── Water Sources ──────────────────────────────────────

export const SOURCE_SEEDS: WaterSource[] = [
  {
    id: "src_tank",
    name: "Main Water Tank",
    name_ar: "خزان المياه الرئيسي",
    type: "tank",
    enabled: true,
    availability: "available",
  },
  {
    id: "src_well",
    name: "Farm Well (Direct)",
    name_ar: "بئر المزرعة (مباشر)",
    type: "well_direct",
    enabled: true,
    availability: "available",
  },
];

// ─── Sensors (Minimal Phase 1 from IO_LIST.md §7) ──────

export const SENSOR_SEEDS: Sensor[] = [
  {
    id: "sensor_tank_level",
    farm_id: "farm_algaroshy",
    zone_id: null,
    code: "TANK_LEVEL_01",
    sensor_type: "level",
    unit: "%",
    location_scope: "tank",
    enabled: true,
  },
  {
    id: "sensor_main_pressure",
    farm_id: "farm_algaroshy",
    zone_id: null,
    code: "MAIN_PRESSURE_01",
    sensor_type: "pressure",
    unit: "bar",
    location_scope: "mainline",
    enabled: true,
  },
  {
    id: "sensor_main_flow",
    farm_id: "farm_algaroshy",
    zone_id: null,
    code: "MAIN_FLOW_01",
    sensor_type: "flow",
    unit: "m³/h",
    location_scope: "mainline",
    enabled: true,
  },
  // One moisture sensor per zone (12 zones = 12 moisture sensors)
  ...ZONE_SEEDS.map((z): Sensor => ({
    id: `sensor_moisture_${z.code.toLowerCase()}`,
    farm_id: "farm_algaroshy",
    zone_id: z.id,
    code: `MOISTURE_${z.code}`,
    sensor_type: "moisture",
    unit: "%",
    location_scope: "zone",
    enabled: true,
  })),
];

// ─── Valves (one per zone) ──────────────────────────────

export const VALVE_SEEDS: Valve[] = ZONE_SEEDS.map((z): Valve => ({
  id: `valve_${z.code.toLowerCase()}`,
  zone_id: z.id,
  code: `VALVE_${z.code}`,
  enabled: true,
  has_open_feedback: true,
  has_close_feedback: true,
}));
